# Generated by Django 5.2 on 2025-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_basketitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="provider_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
